services:
  stdfolio:
    image: stdfolio:latest
    container_name: stdfolio
    build: .
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy

networks:
  proxy:
    external: true
